### ISSUE TITLE
大佬您好，我是小白

### ISSUE THREAD

**Issue by Tacenda5618** [ddiu8081/bilicli#1]
我想问下win10下如何运行这个程序呢，npm安装我似乎只有在服务器上的linux系统使用过，有办法编译成EXE或者有其他方便可视化的方案吗？（例如置顶窗口在最上层之类的，本人水平太低，多有叨扰，辛苦解答了

**Comment by ddiu8081** [comment]
这个程序没有 GUI 图形界面，需要安装 [Node.js 环境](https://nodejs.org/zh-cn/)，并在命令行中运行。

由于设计为无界面程序，可能它并不适合打包为 exe 或执行窗口操作

**Comment by Tacenda5618** [comment]
已经成功部署上了 非常感谢您的解答！
