### ISSUE TITLE
v0.4.1、v0.4.2 无法启动

### ISSUE THREAD

**Issue by CafeAuLait-CC** [ddiu8081/bilicli#4]
`npx bilicli@latest xxx`
 `npx bilicli@0.4.1 xxx`
`npx bilicli@0.4.2 xxx`
使用以上三条命令时，程序直接退出，没有任何输出信息。

`npx bilicli@0.3.2 xxx` 可以正常使用。

**Comment by ddiu8081** [comment]
v0.4 有一个 breaking change: 加入了 lite 界面，且启动命令有了变化

```bash
// 原界面变为了 bilicli live-full xxx
npx bilicli@latest live-full xxx

// 新的 lite 模式
npx bilicli@latest live xxx
```

现在直接退出确实不太合理，我在这个命令加上帮助文档吧

**Comment by CafeAuLait-CC** [comment]
OK，谢谢！
