### ISSUE TITLE
挺好用的，有一些小问题反馈下

### ISSUE THREAD

**Issue by WhiteMinds** [ddiu8081/bilicli#7]
在 mac 下都正常，在 windows 下 cmd / powershell 中 live-full 会有抖动的情况。

另外这个界面挺好看的，用起来也方便直接 npx 就行了，只做一个平台是不是有点可惜，要不再整个斗鱼啥的 🤣。

**Comment by ddiu8081** [comment]
没有 Windows 没测试过... 抖动可能是应用高度超出了窗口高度，导致第一行/最后一行不断重绘？之前在 mac 碰到过这种问题，可以尝试下手动把窗口拉高一些；

个人不玩儿其他平台，所以做其他平台的话可能没精力去维护😥
而且感觉这种命令行应用除 b 站之外的受众不很广了，之后计划做一个 web 版，到时候如果顺手的话会扩一扩平台

**Comment by WhiteMinds** [comment]
拖动过，不过还是会抖，不修的话也问题不大，只用 live 就行
